### ISSUE TITLE
As a user, I would like the app to allow me to add how many people I had dinner with.

### ISSUE THREAD

**Issue by anjinai** [2106-GH-DivvyUp/DivvyUp#3]
- [x] Create a front end component which allows the end user to input the amt/people they had dinner with.
- [x] Create placeholder entries for individuals.  This field will hold the amount each individual owes.

**Comment by mborba1** [comment]
Screen to add how many people to divide by has been created

**Comment by mborba1** [comment]
functionality to divide by number of people and placeholder of the amount for what each individual owes.
